logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testasd
    username: sa
    password:
  h2:
    console:
      enabled: true
#  security:
#    user:
#      name: kane