on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'

      - if: endsWith(github.head_ref, 'master')
        run: |
          echo "ENVIRONMENT=prod >> $GITHUB_ENV
          echo "DESTINATION_CUSTOMER=prod/customer-auth" >> $GITHUB_ENV
      - if: endsWith(github.head_ref, 'feature')
        run: |
          echo "ENVIRONMENT=dev >> $GITHUB_ENV
          echo "DESTINATION_CUSTOMER=dev/customer-auth" >> $GITHUB_ENV

      - name: Check PR Labels
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $ENVIRONMENT
          echo $DESTINATION_CUSTOMER
          echo $GITHUB_ENV

#        run: |
#          echo ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
#          echo ㅋㅌㅊㅋㅌㅊㅋㅌㅊㅋㅌ
