on:
  pull_request:
    types:
      - closed
    branches: [ master ]

jobs:
  deploy:
#    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        env:
          CONTEXT: ${{ toJSON(github)}}
        run: |
          echo LABELS_LENGTH=$(echo $CONTEXT | jq '.event.pull_request.labels | length') >> $GITHUB_ENV
          echo ${{ github.event.pull_request.labels.*.name }}
          echo ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}

      - name: length check
        run: |
          echo $LABELS_LENGTH