on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'

      - if: endsWith(github.head_ref, 'master')
        env:
          ENVIRONMENT: prod
          DESTINATION_CUSTOMER: prod/admin-auth
        run: echo $GITHUB_ENV
      - if: endsWith(github.head_ref, 'feature')
        env:
          ENVIRONMENT: dev
          DESTINATION_CUSTOMER: dev/admin-auth
        run: |
          echo $GITHUB_ENV
          echo ENVIRONMENT
          echo DESTINATION_CUSTOMER

      - name: Check PR Labels
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "ENVIRONMENT-test=test" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
          printf( $GITHUB_ENV )

#        run: |
#          echo ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
#          echo ㅋㅌㅊㅋㅌㅊㅋㅌㅊㅋㅌ
