on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'

      - if: endsWith(github.ref, '/master')
        run: echo "ENVIRONMENT=dev" >> $GITHUB_ENV
      - if: endsWith(github.ref, '/feature')
        run: echo "ENVIRONMENT=dev" >> $GITHUB_ENV

      - name: Check PR Labels
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_ENV"
          echo  ${{ github.ref }}
          echo  ${{ github.head_ref }}

#        run: |
#          echo ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
#          echo ㅋㅌㅊㅋㅌㅊㅋㅌㅊㅋㅌ
