on:
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        run: echo "Check out code"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        env:
          CONTEXT: ${{ toJSON(github)}}
        run: |
          echo $CONTEXT
          echo "ㅁㄴㅇ"