on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        env:
          CONTEXT: ${{ toJSON(github)}}
        run: echo $CONTEXT