on:
  pull_request:
    types:
      - closed
    branches: [ master ]

jobs:
  deploy:
#    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        env:
          CONTEXT: ${{ toJSON(github)}}
        run: |
          echo ${{ github.event.pull_request.labels }}