on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'

      - name: Check PR Labels
        #if: contains(github.event.pull_request.labels.*.name, 'deploy')
        env:
          PR_LABEL_LIST: ${{ toJson(github.event.pull_request.labels.*.name) }}
          PU_LABEL_LIST: ${{ toJson(github.event.push.labels.*.name) }}
        run: |
          echo ${{ env.PR_LABEL_LIST }}
          echo ${{ env.PU_LABEL_LIST }}
          echo ${{ github.event.pull_request.labels.* }}
          echo ${{ github.event.pull_request.labels.*.name }}
          echo ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
          echo '라벨체크 확인 오케이'
