on:
  pull_request:
    types:
      - closed
    branches: [ master ]

jobs:
  deploy:
#    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - if: contains(fromJson('["mast", "feature"]'), github.base_ref)
        run: |
          echo ${{ github.base_ref }}
          echo "OK"
      

