on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        env:
          CONTEXT: ${{ toJSON(github)}}
        run: |
          echo $CONTEXT